version: '3.7'

# Define services
services:
  # App backend service
  app-server:
    container_name: ecommerce-backend
    # Configuration for building the docker image for the backend service
    build:
      context: server # Use an image built from the specified dockerfile in the `server` directory.
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # Forward the exposed port 8081 on the container to port 8081 on the host machine
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - elasticsearch # This service depends on elasticsearch. Start that first.
    environment: # Pass environment variables to the service
      - ECOMMERCE_ES_HOST=host.docker.internal
      - ECOMMERCE_ES_PORT=9200
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Frontend Service
  app-client:
    container_name: ecommerce-frontend
    build:
      context: client # Use an image built from the specified dockerfile in the `client` directory.
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: api/v1
    ports:
      - "9090:80" # Forward the exposed port 80 on the container to port 9090 on the host machine
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend

  # Database Service (Elasticsearch)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - db-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - backend

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

# Volumes
volumes:
  db-data:
    driver: local

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: